import { CoursesBody } from 'models';

export const coursesBodyData: CoursesBody[] = [
	{
		id: '1',
		courseName: 'Computer Graphics',
		category: 'Computer Science',
		lastUpdated: '27-02-2023',
		categoryId: 'development',
		description: 'This course is about computer graphics',
		prerequisites: ['cs321'],
		courseCode: 'cs330',
		status: 'active',
	},
	{
		id: '2',
		courseName: 'Computer Science',
		category: 'Computer Science',
		lastUpdated: '01-02-2023',
		categoryId: 'development',
		description: 'This course is about computer science',
		prerequisites: ['cs322'],
		courseCode: 'cs321',
		status: 'active',
	},
	{
		id: '3',
		courseName: 'Design Patterns',
		category: 'Computer Science',
		lastUpdated: '12-02-2023',
		categoryId: '1',
		description: 'This course is about design patterns',
		prerequisites: ['cs329'],
		courseCode: 'cs331',
		status: 'active',
	},
	{
		id: '4',
		courseName: 'Music Theory',
		category: 'Music',
		lastUpdated: '12-02-2023',
		categoryId: 'music',
		description: 'This course is about music theory',
		prerequisites: ['cs332'],
		courseCode: 'cs333',
		status: 'inactive',
	},
	{
		id: '5',
		courseName: 'Algorithms and Data Structures',
		category: 'Computer Science',
		lastUpdated: '27-02-2023',
		categoryId: '1',
		description: 'This course is about algorithms and data structures',
		prerequisites: ['none'],
		courseCode: 'cs322',
		status: 'inactive',
	},
	{
		id: '6',
		courseName: 'Intodduction to CPR',
		category: 'Health',
		lastUpdated: '27-02-2023',
		categoryId: '1',
		description: 'This course is about CPR',
		prerequisites: ['none'],
		courseCode: 'cs334',
		status: 'active',
	},
];
