import { StudnetsAttendanceTableBodyData } from 'models';

export const studentsTableBodyData: StudnetsAttendanceTableBodyData[] = [
	{
		number: '1',
		name: 'Wagih Mohamed',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+2',
	},
	{
		number: '2',
		name: 'Ali Kehel',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+3',
	},
	{
		number: '3',
		name: 'Shawky Sobhy',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+2',
	},
	{
		number: '4',
		name: 'Mohamed Rezk',
		week1: '0',
		week2: '0',
		week3: '0',
		week4: '0',
		bounses: '-1',
	},
	{
		number: '5',
		name: 'Abd el monem Anwar',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '6',
		name: 'Mohamed Ahmed',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '7',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
	{
		number: '8',
		name: 'Wagih Mohamed',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+2',
	},
	{
		number: '9',
		name: 'Ali Kehel',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+3',
	},
	{
		number: '10',
		name: 'Shawky Sobhy',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+2',
	},
	{
		number: '11',
		name: 'Mohamed Rezk',
		week1: '0',
		week2: '0',
		week3: '0',
		week4: '0',
		bounses: '-1',
	},
	{
		number: '12',
		name: 'Abd el monem Anwar',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '13',
		name: 'Mohamed Ahmed',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '14',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
	{
		number: '15',
		name: 'Wagih Mohamed',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+2',
	},
	{
		number: '16',
		name: 'Ali Kehel',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+3',
	},
	{
		number: '17',
		name: 'Shawky Sobhy',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+2',
	},
	{
		number: '18',
		name: 'Mohamed Rezk',
		week1: '0',
		week2: '0',
		week3: '0',
		week4: '0',
		bounses: '-1',
	},
	{
		number: '19',
		name: 'Abd el monem Anwar',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '20',
		name: 'Mohamed Ahmed',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '21',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
	{
		number: '22',
		name: 'Wagih Mohamed',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+2',
	},
	{
		number: '23',
		name: 'Ali Kehel',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+3',
	},
	{
		number: '24',
		name: 'Shawky Sobhy',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+2',
	},
	{
		number: '25',
		name: 'Mohamed Rezk',
		week1: '0',
		week2: '0',
		week3: '0',
		week4: '0',
		bounses: '-1',
	},
	{
		number: '26',
		name: 'Abd el monem Anwar',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '27',
		name: 'Mohamed Ahmed',
		week1: '1',
		week2: '1',
		week3: '1',
		week4: '1',
		bounses: '+1',
	},
	{
		number: '28',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
	{
		number: '29',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
	{
		number: '30',
		name: 'Mohamed Ali',
		week1: '1',
		week2: '1',
		week3: '0',
		week4: '0',
		bounses: '+1',
	},
];
