import { User } from 'models';

export const usersData: User[] = [
	{
		id: '1',
		firstName: 'John',
		lastName: 'Doe',
		email: 'jhonDoe@gmail.com',
		phoneNumber: '123456789',
		role: 'Teacher',
		lastLogin: '12-03-2020',
		status: 'active',
	},
	{
		id: '2',
		firstName: 'Ahmed',
		lastName: 'Shalaby',
		email: 'ahmedshalaby00@gmail.com',
		phoneNumber: '01117622810',
		role: 'Teacher',
		lastLogin: '01-12-2023',
		status: 'active',
	},
	{
		id: '3',
		firstName: 'Ali',
		lastName: 'Kehel',
		email: 'AliKehel69@gmail.com',
		phoneNumber: '01621908172',
		role: 'Student',
		lastLogin: '01-12-2020',
		status: 'active',
	},
	{
		id: '4',
		firstName: 'Wagih',
		lastName: 'Mohamed',
		email: 'wagihm162@gmail.com',
		phoneNumber: '01115811533',
		role: 'Student',
		lastLogin: '09-03-2020',
		status: 'active',
	},
	{
		id: '5',
		firstName: 'Shawky',
		lastName: 'Sobhy',
		email: 'shawky@gmail.com',
		phoneNumber: '01237291001',
		role: 'Student',
		lastLogin: '09-03-2023',
		status: 'inactive',
	},
];
